### ISSUE TITLE
DATAPLATFORM_HOME variable?

### ISSUE THREAD

**Issue by dobsoft** [gschmutz/kafka-workshop#4]
When I try to start docker with "docker-compose up -d" I get the warning "WARNING: The DATAPLATFORM_HOME variable is not set. Defaulting to a blank string.". And then a lot of log-lines. Including "PermissionError:" and several "Permission denied".

When I use "sudo docker-compose up -d" I don't got the Error in the log-lines. But still the warning about DATAPLATFORM_HOME. But the services are starting(?).
But even then I don't get a connection to "http://#PUBLIC_IP#:28103/" where #PUBLIC_IP# is the result of "curl ipinfo.io/ip".

Did I missed something?

Reinhard

**Comment by gschmutz** [comment]
Hi Reinhard, sorry for the late reply, just saw it today. The DATAPLATFORM_HOME is not mandatory, if will just not display properly in the Markdown page being rendered. But the stack will still work. 

The PUBLIC_IP needs to be the IP address of your docker host, which is exposed to the outside. Did you try to create it on your local machine or on a cloud based VM? On a local machine both PUBLIC_IP and DOCKER_HOST_IP can be the same.
